resources:
  - project.yaml
  - argocd
  - authentik
  - cert-manager
  - coredns
  - democratic-csi
  - device-drivers
  - flannel
  - metallb
  - minio
  - sealed-secrets
  - traefik
  - traefik-forward-auth
